### ISSUE TITLE
test

### ISSUE THREAD

**Issue by 3esmit** [ethereans/github-token#24]

**Comment by commiteth** [comment]
Current balance: 0,00000000
Contract address: 0x15205f9a30337f3038e89edf98234f299faa8b32
![QR Code](http://3esmit2.ddns.net:3000/qr/ethereans/github-token/bounty/24/7bc910220ab1690a1b22ce6ae251d7917d137a45fdc91e153598bebd2679bd6a/qr.png)
Network: Mainnet
To claim this bounty sign up at [http://3esmit2.ddns.net:3000](http://3esmit2.ddns.net:3000)
